- name: "Add Ormuco SSH key"
  authorized_key:
    user: ec2-user
    state: present
    key: http://paste.openstack.org/raw/osn4Yi7NFIb6PsYpRkT8
    exclusive: no
    manage_dir: yes

- name: "Install system packages"
  package:
    name: "{{ ormuco_system_packages }}"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2
  notify: "Start and enable docker service"
  become: true

- meta: flush_handlers
